"""Update Document model fields

Revision ID: 5c5393773dc4
Revises: a8677b35c4eb
Create Date: 2026-04-16 18:51:02.286151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5393773dc4'
down_revision: Union[str, None] = 'a8677b35c4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'file_hash')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
