"""add_company_name_fixed

Revision ID: 82dab891b574
Revises: 5c5393773dc4
Create Date: 2026-04-17 13:28:12.454233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dab891b574'
down_revision: Union[str, None] = '5c5393773dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('company_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_company_name'), 'documents', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_company_name'), table_name='documents')
    op.drop_column('documents', 'company_name')
    # ### end Alembic commands ###
