"""add_user_company_name

Revision ID: 893df2f3a9de
Revises: 4752a9b7f442
Create Date: 2026-04-17 13:46:15.301079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893df2f3a9de'
down_revision: Union[str, None] = '4752a9b7f442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_company_name'), 'users', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_name'), table_name='users')
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
